### ISSUE TITLE
System.InvalidCastException: Can't write CLR type System.DateTimeOffset with handler type TimestampHandler

### ISSUE THREAD

**Issue by hmurt** [b00ted/serilog-sinks-postgresql#14]
I'm getting the following exception when trying to write to PostgreSQL log:

```
2018-07-12T12:38:13.3112351Z Exception while emitting periodic batch from Serilog.Sinks.PostgreSQL.PostgreSQLSink: System.InvalidCastException: Can't write CLR type System.DateTimeOffset with handler type TimestampHandler
   at lambda_method(Closure , NpgsqlTypeHandler , Object , NpgsqlLengthCache& , NpgsqlParameter )
   at Npgsql.TypeHandling.NpgsqlSimpleTypeHandler`1.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter) in C:\projects\npgsql\src\Npgsql\TypeHandling\NpgsqlSimpleTypeHandler.cs:line 236
   at Npgsql.NpgsqlParameter.ValidateAndGetLength() in C:\projects\npgsql\src\Npgsql\NpgsqlParameter.cs:line 553
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlParameter param) in C:\projects\npgsql\src\Npgsql\NpgsqlBinaryImporter.cs:line 244
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.WriteToStream(NpgsqlBinaryImporter writer, IEnumerable`1 entities)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.ProcessEventsByCopyCommand(IEnumerable`1 events, NpgsqlConnection connection)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
```

Here is my config (columnWriters are the same as default):

```
var columnWriters = new Dictionary<string, ColumnWriterBase>
            {
                {"message", new RenderedMessageColumnWriter(NpgsqlDbType.Text) },
                {"message_template", new MessageTemplateColumnWriter(NpgsqlDbType.Text) },
                {"level", new LevelColumnWriter(true, NpgsqlDbType.Varchar) },
                {"raise_date", new TimestampColumnWriter(NpgsqlDbType.Timestamp) },
                {"exception", new ExceptionColumnWriter(NpgsqlDbType.Text) },
                {"properties", new LogEventSerializedColumnWriter(NpgsqlDbType.Jsonb) },
                {"props_test", new PropertiesColumnWriter(NpgsqlDbType.Jsonb) },
                {"machine_name", new SinglePropertyColumnWriter("MachineName", PropertyWriteMethod.ToString, NpgsqlDbType.Text, "l") }
            };

Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .WriteTo.Console()
                .WriteTo.PostgreSQL(loggingConnectionString, "dotnet_core_log", columnWriters, useCopy: false, needAutoCreateTable: true)
                .CreateLogger();
```

I'm using PostgreSQL 9.6, Serilog 2.7.1, Serilog.Sinks.PostgreSQL 1.2.0 and Npgsql 4.0.2.

**Comment by solvingproblemswithtechnology** [comment]
I have the same problem with .Net Core 2.1.1.

**Comment by b00ted** [comment]
Fixed in verion 2
