### ISSUE TITLE
Exception while using SinglePropertyColumnWriter with NpgsqlDbType.Integer

### ISSUE THREAD

**Issue by joelnotified** [b00ted/serilog-sinks-postgresql#15]
Hi!
I'm trying to write a property to an `integer` column. This is my setup:

```
<PackageReference Include="Npgsql" Version="4.0.2" />
<PackageReference Include="Serilog.Extensions.Logging" Version="2.0.2" />
<PackageReference Include="Serilog.Settings.Configuration" Version="2.4.0" />
<PackageReference Include="Serilog.Sinks.Literate" Version="3.0.0" />
<PackageReference Include="Serilog.Sinks.Seq" Version="3.4.0" />
<PackageReference Include="Serilog.Sinks.PostgreSQL" Version="2.0.0" />

... 

IDictionary<string, ColumnWriterBase> columnWriters = new Dictionary<string, ColumnWriterBase>
{
    {"timestamp", new TimestampColumnWriter(NpgsqlDbType.Timestamp) },
    {"testint", new SinglePropertyColumnWriter("MyNumber", PropertyWriteMethod.Raw, NpgsqlDbType.Integer) }
};

...

.WriteTo.PostgreSQL(connectionstring, tableName, columnWriters).Filter.ByIncludingOnly(Matching.FromSource<StatisticsService>())

...

_logger.LogInformation("{MyNumber}", 123);
```

This is my table:

```
CREATE TABLE public.logs (
	id serial NOT NULL,
	timestamp timestamp NOT NULL,
	testint integer NULL,
	CONSTRAINT logs_pkey PRIMARY KEY (id)
);
```

This results in an exception that looks like this:

```
2018-07-19T08:56:44.8478766Z Exception while emitting periodic batch from Serilog.Sinks.PostgreSQL.PostgreSQLSink: System.InvalidCastException: Can't write CLR type Serilog.Events.ScalarValue with handler type Int32Handler
   at lambda_method(Closure , NpgsqlTypeHandler , Object , NpgsqlLengthCache& , NpgsqlParameter )
   at Npgsql.TypeHandling.NpgsqlSimpleTypeHandler`1.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlParameter param)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.WriteToStream(NpgsqlBinaryImporter writer, IEnumerable`1 entities)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.ProcessEventsByCopyCommand(IEnumerable`1 events, NpgsqlConnection connection)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.<EmitBatchAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.<OnTick>d__16.MoveNext()
```

What could I be doing wrong?

**Comment by b00ted** [comment]
Fixed in version 2.0.1
