### ISSUE TITLE
22021: invalid byte sequence for encoding "UTF8": 0x00

### ISSUE THREAD

**Issue by nilmas** [b00ted/serilog-sinks-postgresql#24]
I have configured an example table:

```
CREATE TABLE "log" (
  "id" int8 NOT NULL GENERATED ALWAYS AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
),
  "timestamp" timestamp(6) NOT NULL,
  "level" text COLLATE "pg_catalog"."default" NOT NULL,
  "message" text COLLATE "pg_catalog"."default" NOT NULL,
  "message_template" text COLLATE "pg_catalog"."default",
  "exception" text COLLATE "pg_catalog"."default",
  "log_event" jsonb,
  CONSTRAINT "pk_log" PRIMARY KEY ("id")
)
;
```

Code configuration:

```
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Verbose()
                .WriteTo.PostgreSQL([ConnectionString], [TableName], useCopy: false)
                .CreateLogger();
```
This works.

If I set **useCopy: true** I get the following exception:
```
[timestamp] Exception while emitting periodic batch from Serilog.Sinks.PostgreSQL.PostgreSQLSink: Npgsql.PostgresException (0x80004005): 22021: invalid byte sequence for encoding "UTF8": 0x00
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.ReadMessage(DataRowLoadingMode dataRowLoadingMode) in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 888
   at Npgsql.NpgsqlBinaryImporter.Complete() in C:\projects\npgsql\src\Npgsql\NpgsqlBinaryImporter.cs:line 303
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.ProcessEventsByCopyCommand(IEnumerable`1 events, NpgsqlConnection connection)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.EmitBatchAsync(IEnumerable`1 events)

   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
```

What is the performance implication of using copy vs insert in this context i.e. how much will performance take a hit with useCopy: false?

**Comment by b00ted** [comment]
Unfortunately I haven't any benchmarks. But I have a suggestion about the reason of the error - in ColumnOptions.Default "level" column is integer, so when you try to write message with LogEventLevel.Verbose (which is zero) directly, Postgres does not convert it to text, but get a raw value instead and gets the symbol with 0x00 UTF8 code, which is illegal.

**Comment by nilmas** [comment]
Thanks for responding. Using the following resolves the issue:
... column writers ...
{"[name_for_level]", new LevelColumnWriter(true, NpgsqlDbType.Text) },
{"[name_for_level_id]", new LevelColumnWriter(false, NpgsqlDbType.Integer) },
...
