### ISSUE TITLE
Error on setup

### ISSUE THREAD

**Issue by XanNava** [b00ted/serilog-sinks-postgresql#33]
I am getting the bellow error.

2021-02-02T21:36:39.8231744Z Exception while emitting periodic batch from Serilog.Sinks.PostgreSQL.PostgreSQLSink: System.MissingMethodException: Method not found: 'Void Npgsql.NpgsqlBinaryImporter.Complete()'.
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.ProcessEventsByCopyCommand(IEnumerable`1 events, NpgsqlConnection connection)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.EmitBatchAsync(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()

to replicate I fallowed the guide, and added needAutoCreateTable respectCase. Do I need to specify the public Schema for setup?

 Log.Logger = new LoggerConfiguration()
                    .WriteTo.PostgreSQL(connectionstring, tableName, columnWriters, needAutoCreateTable: true, respectCase: true)
                    .CreateLogger();

**Comment by XanNava** [comment]
Figured it out from ticket https://github.com/b00ted/serilog-sinks-postgresql/issues/11
