### ISSUE TITLE
Method not found: 'Void Npgsql.NpgsqlBinaryImporter.Complete()'.

### ISSUE THREAD

**Issue by omidnasiri** [b00ted/serilog-sinks-postgresql#35]
2021-03-19T09:45:05.0365772Z Exception while emitting periodic batch from Serilog.Sinks.PostgreSQL.PostgreSQLSink: System.MissingMethodException: Method not found: 'Void Npgsql.NpgsqlBinaryImporter.Complete()'.
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.ProcessEventsByCopyCommand(IEnumerable`1 events, NpgsqlConnection connection)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.EmitBatchAsync(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()

**Comment by salihagic** [comment]
Is this being fixed?

**Comment by b00ted** [comment]
fixed in 2.3.0
